<a href="https://colab.research.google.com/github/LCaravaggio/felicidad_y_redes/blob/main/GeoCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2023

In [ ]:
!wget "https://ookla-open-data.s3.amazonaws.com/shapefiles/performance/type=fixed/year=2023/quarter=2/2023-04-01_performance_fixed_tiles.zip"

--2023-09-29 14:25:00--  https://ookla-open-data.s3.amazonaws.com/shapefiles/performance/type=fixed/year=2023/quarter=2/2023-04-01_performance_fixed_tiles.zip
Resolving ookla-open-data.s3.amazonaws.com (ookla-open-data.s3.amazonaws.com)... 52.218.178.201, 52.92.148.89, 52.218.133.57, ...
Connecting to ookla-open-data.s3.amazonaws.com (ookla-open-data.s3.amazonaws.com)|52.218.178.201|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 239553206 (228M) [application/zip]
Saving to: ‘2023-04-01_performance_fixed_tiles.zip’

2023-04-01_performa 100%[===================>] 228.46M  18.5MB/s    in 12s

2023-09-29 14:25:13 (19.0 MB/s) - ‘2023-04-01_performance_fixed_tiles.zip’ saved [239553206/239553206]

In [ ]:
import zipfile
import os

os.listdir()

for file in os.listdir():
    if file.endswith('.zip'):
      zip_ref = zipfile.ZipFile(file, 'r')
      zip_ref.extractall()
      zip_ref.close()

In [ ]:
!pip install simpledbf
from simpledbf import Dbf5
dbf = Dbf5('/content/gps_fixed_tiles.dbf')
df = dbf.to_dataframe()

Requirement already satisfied: simpledbf in /usr/local/lib/python3.10/dist-packages (0.2.6)

In [ ]:
!pip install pyquadkey2

from pyquadkey2 import quadkey

Collecting pyquadkey2
  Downloading pyquadkey2-0.2.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.whl (136 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.5/136.5 kB 2.8 MB/s eta 0:00:00
Installing collected packages: pyquadkey2
Successfully installed pyquadkey2-0.2.2

In [ ]:
def qk_to_geo(quadkey_str, zoom_level):
    qk = quadkey.from_str(quadkey_str)
    lat_lon = qk.to_geo(zoom_level)
    return lat_lon

In [ ]:
df['geo'] = df['quadkey'].apply(qk_to_geo , zoom_level=1)

In [ ]:
import requests
from bs4 import BeautifulSoup

def Citytolatlon(city):
  api_url = 'http://www.geonames.org/search.html?q={}'
  response = requests.get(api_url + city)
  text=""
  if response.status_code == requests.codes.ok:
    soup = BeautifulSoup(response.text, 'html.parser')
    td_elements = soup.find_all('td', nowrap=True)
    count = 0
    for td in td_elements:
      text += td.get_text(strip=True)
      count+=1

      if count == 2:
          break
  else:
      print("Error:", response.status_code, response.text)
  return text

In [ ]:
!pip install latlon3
import latlon

Requirement already satisfied: latlon3 in /usr/local/lib/python3.10/dist-packages (1.0.4)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from latlon3) (1.16.0)
Requirement already satisfied: pyproj in /usr/local/lib/python3.10/dist-packages (from latlon3) (3.6.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from pyproj->latlon3) (2023.7.22)

In [ ]:
from latlon import Latitude, Longitude, string2latlon

In [ ]:
import re

class LL:
    __name__ = 'LatLon'
    def __init__(self, lat, lon, name=None):

        try:
            if lat.type() == 'GeoCoord':
                self.lat = lat
            else:
                raise AttributeError
        except AttributeError:
            self.lat = Latitude(lat)
        try:
            if lon.type() == 'GeoCoord':
                self.lon = lon
            else:
                raise AttributeError
        except AttributeError:
            self.lon = Longitude(lon)
        self.name = name

def toLatLong (texto):
  pattern = r'([SN])\s+(\d+)°\s+(\d+)\'\s+(\d+)\'\'([EW])\s+(\d+)°\s+(\d+)\'\s+(\d+)\'\''
  matches = re.findall(pattern, texto.replace('�','°'))

  if matches:
    direction1, degrees1, minutes1, seconds1, direction2, degrees2, minutes2, seconds2 = matches[0]
    output_str1 = f"{degrees1} {minutes1} {seconds1} {direction1}"
    output_str2 = f"{degrees2} {minutes2} {seconds2} {direction2}"

  else:
    return LL(lat=0, lon=0)

  return string2latlon(output_str1, output_str2, 'd% %m% %S% %H')

In [ ]:
import pandas as pd
base=pd.read_stata('LB2023.dta')

In [ ]:
lista_ciudades=base['ciudad'].unique()

In [ ]:
latsylongs=[]
for ciudad in lista_ciudades:
    # Get the latitude and longitude for the current city
    lat_lon = toLatLong(Citytolatlon(ciudad.encode('latin-1').decode('utf-8')))

    # Append the lat_lon values as a list to the matrix
    latsylongs.append([ciudad, lat_lon.lat, lat_lon.lon])

# Create a DataFrame from the list of lists
ciudades_latlon = pd.DataFrame(latsylongs, columns=['City', 'Latitude', 'Longitude'])

In [ ]:
ciudades_latlon

,City,Latitude,Longitude
0,AR: Buenos Aires-Presidente Peron,-34.91777777777777,-58.37916666666667
1,AR: Capital Federal-Ciudad de Buenos Aires,-34.613055555555555,-58.37722222222222
2,AR: Buenos Aires-Suipacha,-34.75,-59.75
3,AR: Buenos Aires-Necochea,-38.55444444444444,-58.739444444444445
4,AR: TucumÃ¡n-Lules,-26.928611111111113,-65.33833333333332
...,...,...,...
1367,VE: Miranda-Acevedo,10.25,-66.33333333333333
1368,VE: Monagas-Caripe,10.166666666666666,-63.416666666666664
1369,VE: Trujillo-Candelaria,9.618055555555555,-70.35694444444444
1370,VE: Trujillo-Carache,9.666666666666666,-70.33333333333333
1371,VE: Trujillo-PampÃ¡n,9.444722222222222,-70.4775

In [ ]:
ciudades_latlon['Latitude_num']=ciudades_latlon['Latitude'].astype(float)
ciudades_latlon['Longitude_num']=ciudades_latlon['Longitude'].astype(float)

In [ ]:
(ciudades_latlon['Latitude_num'] != 0).sum()

1166

In [ ]:
from scipy.spatial import cKDTree
import numpy as np

kdtree = cKDTree(df['geo'].apply(lambda x: (np.radians(x[0]), np.radians(x[1]))).tolist())

def find_nearest_city(row):
    lat, lon = np.radians(row['Latitude_num']), np.radians(row['Longitude_num'])
    dist, idx = kdtree.query([lat, lon])
    return df.at[idx, 'avg_d_kbps']

ciudades_latlon['avg_d_kbps'] = ciudades_latlon.apply(find_nearest_city, axis=1)

In [ ]:
ciudades_latlon

,City,Latitude,Longitude,Latitude_num,Longitude_num,avg_d_kbps
0,AR: Buenos Aires-Presidente Peron,-34.91777777777777,-58.37916666666667,-34.917778,-58.379167,174179
1,AR: Capital Federal-Ciudad de Buenos Aires,-34.613055555555555,-58.37722222222222,-34.613056,-58.377222,174489
2,AR: Buenos Aires-Suipacha,-34.75,-59.75,-34.750000,-59.750000,11339
3,AR: Buenos Aires-Necochea,-38.55444444444444,-58.739444444444445,-38.554444,-58.739444,103360
4,AR: TucumÃ¡n-Lules,-26.928611111111113,-65.33833333333332,-26.928611,-65.338333,91275
...,...,...,...,...,...,...
1367,VE: Miranda-Acevedo,10.25,-66.33333333333333,10.250000,-66.333333,4933
1368,VE: Monagas-Caripe,10.166666666666666,-63.416666666666664,10.166667,-63.416667,4025
1369,VE: Trujillo-Candelaria,9.618055555555555,-70.35694444444444,9.618056,-70.356944,2675
1370,VE: Trujillo-Carache,9.666666666666666,-70.33333333333333,9.666667,-70.333333,2403
1371,VE: Trujillo-PampÃ¡n,9.444722222222222,-70.4775,9.444722,-70.477500,5188

In [ ]:
ciudades_latlon.to_csv('ciudades_latlon.csv')

# 2018

In [1]:
!wget "https://ookla-open-data.s3.amazonaws.com/shapefiles/performance/type=fixed/year=2019/quarter=1/2019-01-01_performance_fixed_tiles.zip"

--2024-09-17 15:24:33--  https://ookla-open-data.s3.amazonaws.com/shapefiles/performance/type=fixed/year=2019/quarter=1/2019-01-01_performance_fixed_tiles.zip
Resolving ookla-open-data.s3.amazonaws.com (ookla-open-data.s3.amazonaws.com)... 52.92.227.217, 52.218.176.131, 52.92.180.233, ...
Connecting to ookla-open-data.s3.amazonaws.com (ookla-open-data.s3.amazonaws.com)|52.92.227.217|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 290431451 (277M) [application/zip]
Saving to: ‘2019-01-01_performance_fixed_tiles.zip’

2019-01-01_performa 100%[===================>] 276.98M  14.6MB/s    in 19s

2024-09-17 15:24:53 (14.5 MB/s) - ‘2019-01-01_performance_fixed_tiles.zip’ saved [290431451/290431451]

In [2]:
!unzip 2019-01-01_performance_fixed_tiles.zip

Archive:  2019-01-01_performance_fixed_tiles.zip
  inflating: gps_fixed_tiles.dbf
  inflating: gps_fixed_tiles.prj
  inflating: gps_fixed_tiles.shp
  inflating: gps_fixed_tiles.shx

In [3]:
!pip install simpledbf
from simpledbf import Dbf5
dbf = Dbf5('/content/gps_fixed_tiles.dbf')
df = dbf.to_dataframe()

Collecting simpledbf
  Downloading simpledbf-0.2.6.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: simpledbf
  Building wheel for simpledbf (setup.py) ... done
  Created wheel for simpledbf: filename=simpledbf-0.2.6-py3-none-any.whl size=13786 sha256=43d3f6d4e853c3b169b39284aff83b7de2830d56dd5778427927bae5987b1443
  Stored in directory: /root/.cache/pip/wheels/e5/41/13/ebdef29165b9309ec4e235dbff19eca8b6759125b0924ad430
Successfully built simpledbf
Installing collected packages: simpledbf
Successfully installed simpledbf-0.2.6

In [4]:
!pip install pyquadkey2

from pyquadkey2 import quadkey

Collecting pyquadkey2
  Downloading pyquadkey2-0.3.1.tar.gz (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.7/69.7 kB 2.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyquadkey2
  Building wheel for pyquadkey2 (setup.py) ... done
  Created wheel for pyquadkey2: filename=pyquadkey2-0.3.1-cp310-cp310-linux_x86_64.whl size=152485 sha256=c7e5c97161ee01a40208fec26deaaa3c288bc064c77e30db99c156326f4a181c
  Stored in directory: /root/.cache/pip/wheels/e5/43/6c/f04fea698df5b373536f71b64e7499715e4dffcb383ef88ce3
Successfully built pyquadkey2
Installing collected packages: pyquadkey2
Successfully installed pyquadkey2-0.3.1

In [5]:
def qk_to_geo(quadkey_str, zoom_level):
    qk = quadkey.from_str(quadkey_str)
    lat_lon = qk.to_geo(zoom_level)
    return lat_lon

In [6]:
df['geo'] = df['quadkey'].apply(qk_to_geo , zoom_level=1)

In [39]:
df.head()

,quadkey,avg_d_kbps,avg_u_kbps,avg_lat_ms,tests,devices,geo
0,0231113112003202,66216,12490,13,28,4,"(38.492294192361, -90.653686523437)"
1,1322111021111001,102598,37356,13,15,4,"(21.28937435586, 110.357666015625)"
2,3112203030003110,24686,18736,18,162,106,"(-34.921971036163, 138.598022460937)"
3,0320000130321312,17674,13989,78,364,4,"(40.225024210604, -87.632446289062)"
4,0320001332313103,441192,218955,22,14,1,"(38.920955420467, -84.737548828125)"

In [7]:
import requests
from bs4 import BeautifulSoup

def Citytolatlon(city):
  api_url = 'http://www.geonames.org/search.html?q={}'
  response = requests.get(api_url + city)
  text=""
  if response.status_code == requests.codes.ok:
    soup = BeautifulSoup(response.text, 'html.parser')
    td_elements = soup.find_all('td', nowrap=True)
    count = 0
    for td in td_elements:
      text += td.get_text(strip=True)
      count+=1

      if count == 2:
          break
  else:
      print("Error:", response.status_code, response.text)
  return text

In [8]:
!pip install latlon3
import latlon

Collecting latlon3
  Downloading latlon3-1.0.4.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from latlon3) (1.16.0)
Requirement already satisfied: pyproj in /usr/local/lib/python3.10/dist-packages (from latlon3) (3.6.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from pyproj->latlon3) (2024.8.30)
Building wheels for collected packages: latlon3
  Building wheel for latlon3 (setup.py) ... done
  Created wheel for latlon3: filename=latlon3-1.0.4-py3-none-any.whl size=31361 sha256=5880f106b306e8c54f60d43dae5c5d1259521f8bd3ed71b2dfa58327a338d42e
  Stored in directory: /root/.cache/pip/wheels/80/4d/11/7acb2342b2d16d9253d5cb76bbe83de3b7666bf57e27592ef6
Successfully built latlon3
Installing collected packages: latlon3
Successfully installed latlon3-1.0.4

In [9]:
from latlon import Latitude, Longitude, string2latlon

In [31]:
import re

class LL:
    __name__ = 'LatLon'
    def __init__(self, lat, lon, name=None):

        try:
            if lat.type() == 'GeoCoord':
                self.lat = lat
            else:
                raise AttributeError
        except AttributeError:
            self.lat = Latitude(lat)
        try:
            if lon.type() == 'GeoCoord':
                self.lon = lon
            else:
                raise AttributeError
        except AttributeError:
            self.lon = Longitude(lon)
        self.name = name

def toLatLong(texto):
    pattern = r"([NS])\s*(\d+)°\s*(\d+)'\s*(\d+)''([EW])\s*(\d+)°\s*(\d+)'\s*(\d+)''"
    matches = re.findall(pattern, texto.replace('′', "'"))

    if matches:
        direction1, degrees1, minutes1, seconds1, direction2, degrees2, minutes2, seconds2 = matches[0]
        output_str1 = f"{degrees1} {minutes1} {seconds1} {direction1}"
        output_str2 = f"{degrees2} {minutes2} {seconds2} {direction2}"

        # Asegúrate de que string2latlon sea la función correcta para convertir el formato
        return string2latlon(output_str1, output_str2, 'd% %m% %S% %H')
    else:
        return LL(lat=0, lon=0)  # Asegúrate de que LL esté definido

In [12]:
import pandas as pd
base=pd.read_stata('LB2018 2.dta')

<ipython-input-12-13f5e7ddc7ff>:2: UnicodeWarning:
One or more strings in the dta file could not be decoded using utf-8, and
so the fallback encoding of latin-1 is being used.  This can happen when a file
has been incorrectly encoded by Stata or some other software. You should verify
the string values returned are correct.
  base=pd.read_stata('LB2018 2.dta')

In [13]:
lista_ciudades=base['city'].unique()

In [26]:
Citytolatlon(lista_ciudades[0]).replace('′', "'")

"S 34° 36' 47''W 58° 22' 38''"

In [29]:
toLatLong(Citytolatlon(lista_ciudades[1])).lat

[('S', '34', '37', '4', 'W', '58', '28', '38')]

Latitude -34.617777777777775

In [32]:
latsylongs=[]
for ciudad in lista_ciudades:
    # Get the latitude and longitude for the current city
    lat_lon = toLatLong(Citytolatlon(ciudad.encode('latin-1').decode('latin-1')))


    # Append the lat_lon values as a list to the matrix
    latsylongs.append([ciudad, lat_lon.lat, lat_lon.lon])

# Create a DataFrame from the list of lists
ciudades_latlon = pd.DataFrame(latsylongs, columns=['City', 'Latitude', 'Longitude'])

In [33]:
ciudades_latlon

,City,Latitude,Longitude
0,AR: Capital Federal-Ciudad de Buenos Aires,-34.613055555555555,-58.37722222222222
1,AR: Buenos Aires-Gran Buenos Aires,-34.617777777777775,-58.477222222222224
2,AR: Cordoba-Gran Cordoba,-31.408055555555553,-64.21555555555555
3,AR: Santa Fe-Gran Rosario,-32.975,-60.681666666666665
4,AR: Mendoza-Gran Mendoza,-32.888888888888886,-68.84166666666667
...,...,...,...
1060,VE: Bolivar-Piar,6.60361111111111,-62.727222222222224
1061,VE: Apure-San Fernando,7.887777777777776,-67.47222222222223
1062,VE: Apure-Biruaca,7.844722222222222,-67.51666666666667
1063,VE: Apure-Achaguas,7.779166666666667,-68.22361111111111
1064,,55.733333333333334,-102.78361111111111

In [34]:
ciudades_latlon['Latitude_num']=ciudades_latlon['Latitude'].astype(float)
ciudades_latlon['Longitude_num']=ciudades_latlon['Longitude'].astype(float)

In [35]:
(ciudades_latlon['Latitude_num'] != 0).sum()

907

In [43]:
from scipy.spatial import cKDTree
import numpy as np

# Construir el cKDTree utilizando las coordenadas geográficas en radianes
kdtree = cKDTree(df['geo'].apply(lambda x: (np.radians(x[0]), np.radians(x[1]))).tolist())

# Definir la función para encontrar la ciudad más cercana
def find_nearest_city(row):
    lat, lon = np.radians(row['Latitude_num']), np.radians(row['Longitude_num'])
    dist, idx = kdtree.query([lat, lon])
    return [df.at[idx, 'avg_d_kbps'], df.at[idx, 'avg_u_kbps'], df.at[idx, 'avg_lat_ms'], df.at[idx, 'tests'], df.at[idx, 'devices']]

# Aplicar la función y crear nuevas columnas con los resultados descompuestos
ciudades_latlon[['avg_d_kbps', 'avg_u_kbps', 'avg_lat_ms', 'tests', 'devices']] = pd.DataFrame(ciudades_latlon.apply(find_nearest_city, axis=1).tolist(), index=ciudades_latlon.index)

In [44]:
ciudades_latlon

,City,Latitude,Longitude,Latitude_num,Longitude_num,avg_d_kbps,avg_u_kbps,avg_lat_ms,test,devices
0,AR: Capital Federal-Ciudad de Buenos Aires,-34.613055555555555,-58.37722222222222,-34.613056,-58.377222,39905,9198,25,156,69
1,AR: Buenos Aires-Gran Buenos Aires,-34.617777777777775,-58.477222222222224,-34.617778,-58.477222,40972,16806,15,50,13
2,AR: Cordoba-Gran Cordoba,-31.408055555555553,-64.21555555555555,-31.408056,-64.215556,28016,4160,22,13,4
3,AR: Santa Fe-Gran Rosario,-32.975,-60.681666666666665,-32.975000,-60.681667,11299,2844,18,3,2
4,AR: Mendoza-Gran Mendoza,-32.888888888888886,-68.84166666666667,-32.888889,-68.841667,7240,3767,66,93,48
...,...,...,...,...,...,...,...,...,...,...
1060,VE: Bolivar-Piar,6.60361111111111,-62.727222222222224,6.603611,-62.727222,16,60,1799,2,1
1061,VE: Apure-San Fernando,7.887777777777776,-67.47222222222223,7.887778,-67.472222,5887,11553,111,1,1
1062,VE: Apure-Biruaca,7.844722222222222,-67.51666666666667,7.844722,-67.516667,1838,272,185,2,1
1063,VE: Apure-Achaguas,7.779166666666667,-68.22361111111111,7.779167,-68.223611,4287,851,150,1,1
1064,,55.733333333333334,-102.78361111111111,55.733333,-102.783611,5120,955,30,2,1

In [45]:
ciudades_latlon.to_csv('ciudades_latlon 2018.csv')